version: '3'

services:
  mysql:
    image: mysql:5.7
    volumes:
      # - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysql_data:/var/lib/mysql
      - ./sql:/tmp/sql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    # environment:
    #   - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app

volumes:
  mysql_data:
  grafana_data:
